@startuml

' Class diagram: AddressBook -> UniquePersonList -> Person and compositions

class AddressBook {
    - persons : UniquePersonList
    + getPersonList()
}

class UniquePersonList {
    - internalList : List<Person>
    + add(p : Person)
    + remove(p : Person)
}

class Person {
    - name : Name
    - phone : Phone
    - email : Email
    - yearOfStudy : int
    - faculty : String
    - address : Address
    - tags : Set<Tag>
    - isPresent : boolean
    - points : Points
}

' Value objects
class Name
class Phone
class Email
class Address
class Tag
class Points

' Composition relationships
AddressBook *-- UniquePersonList
UniquePersonList *-- Person
Person *-- Name
Person *-- Phone
Person *-- Email
Person *-- Address
Person *-- Points
Person o-- Tag

@enduml
