@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

' Simplified Model class diagram for ClubTrack / AddressBook slice

package Model {
	interface "<<interface>>\nModel" as Model
	interface "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
	interface "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs

	class AddressBook {
		- persons : UniquePersonList
		+ getPersonList() : ObservableList<Person>
	}

	class ModelManager {
		- addressBook : AddressBook
		- userPrefs : UserPrefs
		- filteredPersons : FilteredList<Person>
		+ getFilteredPersonList() : ObservableList<Person>
		+ updateFilteredPersonList(p : Predicate<Person>) : void
	}

	class UserPrefs {
		- guiSettings : GuiSettings
		- addressBookFilePath : Path
		+ getAddressBookFilePath() : Path
	}

	class UniquePersonList {
		- internalList : List<Person>
		+ add(p : Person)
		+ remove(p : Person)
	}

	class Person {
		- name : Name
		- phone : Phone
		- email : Email
		- address : Address
		- yearOfStudy : int
		- faculty : String
		- tags : Set<Tag>
		- isPresent : boolean
		- points : Points
		+ getName() : Name
		+ getPoints() : Points
	}

	' Value objects
	class Name
	class Phone
	class Email
	class Address
	class Tag
	class YearOfStudy
	class Faculty
	class Points

	' Relationships
	ModelManager ..|> Model
	AddressBook .up.|> ReadOnlyAddressBook
	UserPrefs .up.|> ReadOnlyUserPrefs

	ModelManager --> "1" AddressBook
	ModelManager --> "1" UserPrefs
	AddressBook *--> "1" UniquePersonList
	UniquePersonList --> "*" Person
	Person *-- Name
	Person *-- Phone
	Person *-- Email
	Person *-- Address
	Person *-- Points
	Person *-- Tag
}

@enduml
